FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/build/libs/*.jar ./app.jar
EXPOSE 8081
CMD ["./gradlew", "clean", "test"]

FROM gradle:7.5.1-jdk11 AS build
COPY --chown=gradle:gradle . /app
WORKDIR /app

